services:
  db:
    image: postgres:15-alpine

    env_file:
      - .env
         
    volumes:
      - postgres_data:/var/lib/postgresql/data 
  
  fastapi_app:
    build: .
    depends_on:
      - db 
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data: